### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by ridalarry** [TechzoneMC/SonarPet#14] opened 2016-03-29 18:05 UTC
I am having a server on 1.8.8 latest with no other plugins and im having the following issues:
1) Notifing me for update of the old echopet version
2) If I spawn a pet I get internal error
3) If I right click a pet or do /pet menu I get an expectation in console
4) If I move while having a pet the server close
5) I can have multiple pets
6) When I do /pet remove it will say I has no pet even though I do
7) WIther pet crash the server
8) If I leave the server and have a pet the server crash
console logs:
for the wither issue http://pastebin.com/HNu01rfY
for leaving the server while having a pet http://pastebin.com/PYPTYJrv
for all the other issues http://pastebin.com/UQ8Q8sps
Version I was using:
https://github.com/TechzoneMC/SonarPet/releases

UPDATE: I have used the dev build version and seems to have the wither issue fixed, but still crashing the server if I moved. Also the update issue is fixed on that version.

**Comment by Techcable** [comment] 2016-03-31 15:56
Please create seperate issues next time.
The first error is a  duplicate of #3
The second error is a duplicate of #12 
The third error is a duplicate of #9
The issue with update notifications is a duplicate of #15

**Closed by Techcable** 2016-03-31 15:56 UTC
