### ISSUE TITLE
Unable to teleport when riding a pet, or having one on your head.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#44] opened 2016-05-16 20:15 UTC
Brief Description:unable to teleport when riding pets or having pets on your head

Instructions:
1. Spawn a pet
2. Open the Pet Menu
3. Choose either Hat Pet or Ride Pet
4. Do either /tpa, /home, /warp, or go through warps at spawn

How many times did you recreate this bug?:everytime

Result:unable to teleport
Edit: also unable to teleport after removing pet from head and hiding pet until after relog

Expected Result:teleport with(out) pet

https://www.ecocitycraft.com/forum/threads/bug-report-pet-unable-to-teleport-when-riding-pet-on-hat.150369/

**Comment by Techcable** [comment] 2016-05-23 21:09
Duplicate of #29 
Once again, this is a **vanilla bug**, that I can't fix.

**Closed** 2016-05-23 21:09 UTC
Labels: invalid, vanilla-issue
