### ISSUE TITLE
/pet selector issues

### ISSUE THREAD

**Issue by L4BORG** [TechzoneMC/SonarPet#10] opened 2016-03-27 00:39 UTC
http://pastebin.com/gJ2sT4SK

```
[01:38:16 INFO]: This server is running CraftBukkit version git-TacoSpigot-"e026d35" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[01:38:16 INFO]: Checking version, please wait...
[01:38:18 INFO]: You are 7 commit(s) behind
```

Pets would still get spawned... multiple times even... I had 2 bats.

**Comment by Techcable** [comment] 2016-03-27 05:24
Duplicate of #9

**Closed by Techcable** 2016-03-27 05:24 UTC
Labels: duplicate
